// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ICronCache is an autogenerated mock type for the ICronCache type
type ICronCache struct {
	mock.Mock
}

// AcquireLock provides a mock function with given fields: key, value
func (_m *ICronCache) AcquireLock(key string, value string) bool {
	ret := _m.Called(key, value)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ReleaseLock provides a mock function with given fields: key, client
func (_m *ICronCache) ReleaseLock(key string, client string) {
	_m.Called(key, client)
}
