// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IUserController is an autogenerated mock type for the IUserController type
type IUserController struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: w, r
func (_m *IUserController) DeleteUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetUser provides a mock function with given fields: w, r
func (_m *IUserController) GetUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetUsers provides a mock function with given fields: w, r
func (_m *IUserController) GetUsers(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// PostUser provides a mock function with given fields: w, r
func (_m *IUserController) PostUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// PutUser provides a mock function with given fields: w, r
func (_m *IUserController) PutUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
