// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IWalletController is an autogenerated mock type for the IWalletController type
type IWalletController struct {
	mock.Mock
}

// BlockWallet provides a mock function with given fields: w, r
func (_m *IWalletController) BlockWallet(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetWallet provides a mock function with given fields: w, r, getWithUserId
func (_m *IWalletController) GetWallet(w http.ResponseWriter, r *http.Request, getWithUserId bool) {
	_m.Called(w, r, getWithUserId)
}

// PostWallet provides a mock function with given fields: w, r
func (_m *IWalletController) PostWallet(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UnBlockWallet provides a mock function with given fields: w, r
func (_m *IWalletController) UnBlockWallet(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
