// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/WalletService/model"
	mock "github.com/stretchr/testify/mock"
)

// IWalletCache is an autogenerated mock type for the IWalletCache type
type IWalletCache struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *IWalletCache) Get(key int) *model.Wallet {
	ret := _m.Called(key)

	var r0 *model.Wallet
	if rf, ok := ret.Get(0).(func(int) *model.Wallet); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *IWalletCache) Set(key int, value *model.Wallet) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *model.Wallet) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
